### ISSUE TITLE
coclist gfiles : ERR_CHILD_PROCESS_STDIO_MAXBUFFER

### ISSUE THREAD

**Issue by grimgort** [neoclide/coc-git#162]
Hello,

I have a large project with almost versioned file and i have this error : Error on coclist gfiles : Error: exited with ERR_CHILD_PROCESS_STDIO_MAXBUFFER

coc-gît 2.2.0

Thanks :)

**Comment by cigam** [comment]
Same:
```
 2021-02-09T15:14:42.798 INFO (pid:99924) [services] - service clangd started
    9 2021-02-09T15:14:42.817 INFO (pid:99924) [coc-git] - Looking for git in: git
   10 2021-02-09T15:14:42.884 INFO (pid:99924) [plugin] - coc.nvim 0.0.80-6e5a2aaeb5 initialized with node: v13.0.1 after 241ms
   11 2021-02-09T15:14:42.893 INFO (pid:99924) [attach] - receive notification: registNotification [ 'cquery', '$cquery/publishSemanticHighlighting' ]
   12 2021-02-09T15:14:42.893 INFO (pid:99924) [attach] - receive notification: registNotification [ 'cquery', '$cquery/setInactiveRegions' ]
   13 2021-02-09T15:14:42.893 INFO (pid:99924) [attach] - receive notification: registNotification [ 'ccls', '$ccls/publishSemanticHighlight' ]
   14 2021-02-09T15:14:42.893 INFO (pid:99924) [attach] - receive notification: registNotification [ 'ccls', '$ccls/publishSkippedRanges' ]
   15 2021-02-09T15:14:43.292 INFO (pid:99924) [attach] - receive notification: highlight []
   16 2021-02-09T15:14:43.546 INFO (pid:99924) [attach] - receive notification: listResume []
   17 2021-02-09T15:14:46.737 INFO (pid:99924) [attach] - receive notification: listResume []
   18 2021-02-09T15:15:04.544 INFO (pid:99924) [attach] - receive notification: openList []
   19 2021-02-09T15:15:10.913 INFO (pid:99924) [attach] - receive notification: openList [ 'gfiles' ]
   20 2021-02-09T15:15:20.632 INFO (pid:99924) [attach] - receive notification: openList [ 'buffers' ]
   21 2021-02-09T15:15:24.576 INFO (pid:99924) [attach] - receive notification: openList []
   22 2021-02-09T15:15:26.210 INFO (pid:99924) [attach] - receive notification: openList [ 'gfiles' ]
   23 2021-02-09T15:15:26.291 ERROR (pid:99924) [list-manager] - Error: exited with ERR_CHILD_PROCESS_STDIO_MAXBUFFER
   24
   25     at /Users/bkemper/.config/coc/extensions/node_modules/coc-git/lib/index.js:4631:16
   26     at ChildProcess.exithandler (child_process.js:302:5)
   27     at ChildProcess.emit (events.js:210:5)
   28     at maybeClose (internal/child_process.js:1028:16)
   29     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
   30 2021-02-09T15:16:03.844 INFO (pid:99924) [attach] - receive notification: highlight []
   31 2021-02-09T15:17:15.116 INFO (pid:99924) [attach] - receive notification: highlight []
   32 2021-02-09T15:17:50.567 INFO (pid:99924) [attach] - receive notification: openList []
   33 2021-02-09T15:17:52.423 INFO (pid:99924) [attach] - receive notification: openList [ 'gstatus' ]
   34 2021-02-09T15:17:54.914 ERROR (pid:99924) [list-manager] - Error: exited with ERR_CHILD_PROCESS_STDIO_MAXBUFFER
   35
   36     at /Users/bkemper/.config/coc/extensions/node_modules/coc-git/lib/index.js:4631:16
   37     at ChildProcess.exithandler (child_process.js:302:5)
   38     at ChildProcess.emit (events.js:210:5)
   39     at maybeClose (internal/child_process.js:1028:16)
   40     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

```
