### ISSUE TITLE
Error on BufWritePost: Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by sinetoami** [neoclide/coc-git#98]
## Prompt error
```
[coc.nvim] error: Error on BufWritePost: Cannot read property 'uri' of undefined                                                                              
TypeError: Cannot read property 'uri' of undefined                                                                                                            
    at /home/snio/.config/coc/extensions/node_modules/coc-git/lib/index.js:166:21                                                                             
    at /home/snio/.cache/dein/repos/github.com/neoclide/coc.nvim/lib/events.js:73:49                                                                          
    at new Promise (<anonymous>)                                                                                                                              
    at /home/snio/.cache/dein/repos/github.com/neoclide/coc.nvim/lib/events.js:68:24                                                                          
    at /home/snio/.cache/dein/repos/github.com/neoclide/coc.nvim/lib/events.js:42:28                                                                          
    at Array.map (<anonymous>)                                                                                                                                
    at Events.fire (/home/snio/.cache/dein/repos/github.com/neoclide/coc.nvim/lib/events.js:41:39)                                                            
    at NeovimClient.<anonymous> (/home/snio/.cache/dein/repos/github.com/neoclide/coc.nvim/lib/attach.js:47:40)                                               
    at NeovimClient.emit (events.js:321:20)                                                                                                                   
    at NeovimClient.emitNotification (/home/snio/.cache/dein/repos/github.com/neoclide/coc.nvim/node_modules/@chemzqm/neovim/lib/api/client.js:165:18)
```
## coc.nvim config
```
call dein#add('neoclide/coc.nvim', { 'build': 'yarn install --frozen-lockfile' })

"" coc.nvim
"" ***********************************************************
" using nerd-fonts MesloLGSDZ
let g:coc_status_warning_sign = ' '
let g:coc_status_error_sign = ' '

let g:coc_global_extensions = [
      \ 'coc-prettier',
      \ 'coc-eslint',
      \ 'coc-tsserver',
      \ 'coc-tslint-plugin',
      \ 'coc-css', 
      \ 'coc-html',
      \ 'coc-json',
      \ 'coc-snippets',
      \ 'coc-ultisnips',
      \ 'coc-git',
      \ ]

"" coc-prettier
command! -nargs=0 Prettier :CocCommand prettier.formatFile
nmap <leader>f :CocCommand prettier.formatFile<cr>

"" Remap for format selected region
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

"" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

"" diagnostics navigation
nmap <silent> [c <Plug>(coc-diagnostic-prev)
nmap <silent> ]c <Plug>(coc-diagnostic-next)
nmap <leader>qf  <Plug>(coc-fix-current)

"" rename
nmap <silent> <leader>rn <Plug>(coc-rename)

"" Snippets
imap <C-l> <Plug>(coc-snippets-expand)

"" Use K to show documentation in preview window
nnoremap <silent> K :call <SID>show_documentation()<CR>
" Show documentation wrap {{
function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
        execute 'h '.expand('<cword>')
    else
        call CocAction('doHover')
    endif
endfunction
" }}

"" tab completion
inoremap <silent><expr> <TAB>
    \ pumvisible() ? "\<C-n>" :
    \ <SID>check_back_space() ? "\<TAB>" :
    \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
" tab completion wrap {{
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction
" }}

"" multiple cursors
nmap <silent> <C-c> <Plug>(coc-cursors-position)
nmap <expr> <silent> <C-A-d> <SID>select_current_word()
" Wrap multiple cursors like VSCode {{
function! s:select_current_word()
  if !get(g:, 'coc_cursors_activated', 0)
    return "\<Plug>(coc-cursors-word)"
  endif
  return "*\<Plug>(coc-cursors-word):nohlsearch\<CR>"
endfunction
" }}
```
## coc-settings.json
```
{
  "git.branchCharacter": "⎇ ",
  "git.enableGutters": true,
  "git.addedSign.text": "┃",
  "git.changedSign.text": "┃",
  "git.removedSign.text": "",
  "git.changeRemovedSign.text": "",
  "diagnostic.errorSign": "✖",
  "diagnostic.warningSign": "●",
  "diagnostic.infoSign": "●",
  "diagnostic.hintSign": "○",
  "emmet.includeLanguages": {
    "javascript": "javascriptreact",
    "typescript": "typescriptreact"
  },
  "languageserver": {
    "golang": {
      "command": "gopls",
      "rootPatterns": ["go.mod", ".vim/", ".git/", ".hg/"],
      "filetypes": ["go"],
      "initializationOptions": { "usePlaceholders": true }
    }
  },
  "snippets.snipmate.enable": false,
  "snippets.ultisnips.directories": [ "UltiSnips", "gosnippets/UltiSnips" ],
  "coc.preferences.colorSupport": true,
  "coc.preferences.formatOnSaveFiletypes": [
    "css",
    "scss",
    "Markdown"
  ]
}
```

## Explanation
This error throws up when I have `coc-git` installed and it's gone when I uninstall it. I've tried to install the recommended release of `coc.nvim` and had the same error. I've tried to new fresh installs of `coc.nvim` and `coc-git`. I supose this happens only inside a JS/TS project directory, because not happens when I was inside a Golang project directory.

Thanks a lot for your attention. :+1:

**Comment by sinetoami** [comment]
Thank you, @chemzqm. Works great.
